package com.ws.chelloword;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint; 
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-02-28T01:56:56.139+08:00
 * Generated source version: 3.1.5
 * 
 */
@WebServiceClient(name = "HelloWordServiceImpl", 
                  wsdlLocation = "file:/G:/java/webservice/wsdl/helloword.wsdl",
                  targetNamespace = "http://helloworld.ws.com") 
public class HelloWordServiceImpl extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://helloworld.ws.com", "HelloWordServiceImpl");
    public final static QName PortName = new QName("http://helloworld.ws.com", "portName");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8081/userApp/services/HelloWordServiceImpl?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloWordServiceImpl.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8081/userApp/services/HelloWordServiceImpl?wsdll");
        }
        WSDL_LOCATION = url;
    }

    public HelloWordServiceImpl(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloWordServiceImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWordServiceImpl() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public HelloWordServiceImpl(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HelloWordServiceImpl(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HelloWordServiceImpl(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns HelloWordServiceImplPortType
     */
    @WebEndpoint(name = "portName")
    public HelloWordServiceImplPortType getPortName() {
        return super.getPort(PortName, HelloWordServiceImplPortType.class);
    }

    /**;
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWordServiceImplPortType
     */
    @WebEndpoint(name = "portName")
    public HelloWordServiceImplPortType getPortName(WebServiceFeature... features) {
        return super.getPort(PortName, HelloWordServiceImplPortType.class, features);
    }

}
