package com.ws.chelloword;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-02-28T01:56:56.129+08:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://helloworld.ws.com", name = "HelloWordServiceImplPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWordServiceImplPortType {

    @WebResult(name = "out", targetNamespace = "http://helloworld.ws.com")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://helloworld.ws.com", className = "com.ws.chelloword.GetUser")
    @WebMethod
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://helloworld.ws.com", className = "com.ws.chelloword.GetUserResponse")
    public com.ws.chelloword.ArrayOfCUser getUser(
        @WebParam(name = "in0", targetNamespace = "http://helloworld.ws.com")
        com.ws.chelloword.People in0,
        @WebParam(name = "in1", targetNamespace = "http://helloworld.ws.com")
        com.ws.chelloword.ArrayOfHouse in1
    );
}
