
package com.ws.chelloword;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-02-28T01:56:56.071+08:00
 * Generated source version: 3.1.5
 * 
 */
public final class HelloWordServiceImplPortType_PortName_Client {

    private static final QName SERVICE_NAME = new QName("http://helloworld.ws.com", "HelloWordServiceImpl");

    private HelloWordServiceImplPortType_PortName_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = HelloWordServiceImpl.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
        HelloWordServiceImpl ss = new HelloWordServiceImpl(wsdlURL, SERVICE_NAME);
        HelloWordServiceImplPortType port = ss.getPortName();  
        
        {
        System.out.println("Invoking getUser...");
        com.ws.chelloword.People _getUser_in0 = null;
        com.ws.chelloword.ArrayOfHouse _getUser_in1 = null;
        com.ws.chelloword.ArrayOfCUser _getUser__return = port.getUser(_getUser_in0, _getUser_in1);
        System.out.println("getUser.result=" + _getUser__return);
        }

        System.exit(0);
    }

}
